### ISSUE TITLE
按照步骤运行项目失败

### ISSUE THREAD

**Issue by scau009** [Exrick/xmall-front#1]
npm run dev 后报错,如下

**
root@gzr-Aspire-V5-552G:/var/www/html/vue-mall# npm run dev

> vue-node-mall@1.0.0 dev /var/www/html/vue-mall
> node build/dev-server.js

[HPM] Proxy created: /users/*  ->  http://mall.yucccc.com:3333/
[HPM] Proxy created: /goods/*  ->  http://mall.yucccc.com:3333
> Starting dev server...

 ERROR  Failed to compile with 1 errors                                 20:49:21

This dependency was not found:

* /page/login/login in ./src/router/index.js

To install it, you can run: npm install --save /page/login/login
> Listening at http://localhost:9999

**
浏览器显示 cannot get /
请问如何解决?

**Comment by Exrick** [comment]
请确保6个服务启动成功 且前台端口修改正确
