### ISSUE TITLE
npm无法build，cnpm使用run dev启动后端口正常监听，但是页面白屏

### ISSUE THREAD

**Issue by f8q8** [Exrick/xmall-front#10]
我使用npm install，会有一大堆错误。使用cnpm instlall，正常，使用cnpm run build正常，使用cnpm run dev的时候，有如下错误：哪位老哥见过了，帮忙给解决下，谢谢，哈
[root@c629d66f26ee xmall-front]# cnpm run dev

> vue-node-mall@1.0.0 dev /xmall/code/xmall-front
> node build/dev-server.js

[HPM] Proxy created: /member/*  ->  http://127.0.0.1:7777
[HPM] Proxy created: /goods/*  ->  http://127.0.0.1:7777
> Starting dev server...

 DONE  Compiled successfully in 7562ms                                                                                                                       05:39:55

> Listening at http://localhost:9999

(node:4408) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.<anonymous> (/xmall/code/xmall-front/node_modules/_opn@4.0.2@opn/index.js:83:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
(node:4408) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4408) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Exrick** [comment]
删除依赖并用cnpm重试

**Comment by zxl78585** [comment]
已经解决了，是我的xmall-front-web启动的有问题，后来，调整后，就正常了。谢谢

**Comment by niumang** [comment]
> web

楼主后来怎么解决的啊
