### ISSUE TITLE
登录部门  验证码内容出不来？请问是什么原因

### ISSUE THREAD

**Issue by Joyeuxman** [Exrick/xmall-front#15]
登录部门  验证码内容出不来？请问是什么原因
![que1](https://user-images.githubusercontent.com/21262781/44012120-6cb98d38-9eef-11e8-90ae-96f4870407f7.png)
![que2](https://user-images.githubusercontent.com/21262781/44014476-be07e5fe-9efe-11e8-959c-76ce64d1a7cb.png)
![que1](https://user-images.githubusercontent.com/21262781/44014475-bd9ab998-9efe-11e8-9ef2-1cc1c48e4c6b.png)

**Comment by Joyeuxman** [comment]
ok  已解决

**Comment by zhaoyuan1209** [comment]
请问你是什么原因出错的呢？是因为redis没有链接成功？还是极验配置？我没有看到极验配置需要配置什么呀

**Comment by tank2737** [comment]
> 极验配置

要配置id和秘钥，貌似收费的，直接干掉吧
