### ISSUE TITLE
node用哪个版本？

### ISSUE THREAD

**Issue by marie0119** [Exrick/xmall-front#2]
我打开项目右下角有聊天，页面一片空白，
是我Node版本不对吗？
你node装几点几的，我的是v6.9.5

**Comment by chinasonglei** [comment]
@marie0119 你后台项目没有启动   在config/index.js里面配置后台项目路劲  他的服务器管理所以看不到东西

**Comment by Exrick** [comment]
请确保6个服务启动成功 且前台端口修改正确

**Comment by weijipeng** [comment]
v8.17.0可以运行
