### ISSUE TITLE
toFixed

### ISSUE THREAD

**Issue by isMyShell** [Exrick/xmall-front#6]
![image](https://user-images.githubusercontent.com/20751520/39503472-b877ed20-4df8-11e8-9d12-abe38eea8127.png)
在 mallGoods.vue 组件中 `msg.salePrice` 是字符串，使用`toFixed`会报错， 使用`Number(msg.salePrice).toFixed(2)`解决掉了

**Comment by Exrick** [comment]
已采纳 感谢！
