### ISSUE TITLE
JDK1.8，语法出错

### ISSUE THREAD

**Issue by chenxuezhou** [Exrick/xmall-front#9]
[ERROR] /E:/前后端商场管理系统/xmall-master/xmall-manager/xmall-manager-service/src/main/java/cn/exrick/manager/service/impl/ItemServiceImpl.java:[249,69] 从内部类中访问本地变量type; 需要被声明为最终类型
[ERROR] /E:/前后端商场管理系统/xmall-master/xmall-manager/xmall-manager-service/src/main/java/cn/exrick/manager/service/impl/ItemServiceImpl.java:[249,93] 从内部类中访问本地变量id; 需要被声明为最终类型

**Comment by Exrick** [comment]
请确保6个服务启动成功 且前台端口修改正确

**Comment by chenxuezhou** [comment]
好像是有错误的，不过我已经跑起来了！
